### ISSUE TITLE
Leccion04: Sobreescritura de métodos Overriding y Ejercicio

### ISSUE THREAD

**Issue by magalicard** [CodeSystem2022/SharkDevelop3#20]

**Comment by meliriera** [comment]
Hecho! ![bitmoji](https://sdk.bitmoji.com/render/panel/563d9c61-ebea-42c6-8a90-28654d5306b0-95c306cf-7bf5-4041-8689-e525dbe362ea-v1.png?transparent=1&palette=1&width=246)![bitmoji](https://sdk.bitmoji.com/render/panel/563d9c61-ebea-42c6-8a90-28654d5306b0-95c306cf-7bf5-4041-8689-e525dbe362ea-v1.png?transparent=1&palette=1&width=246)
